name: Node.js CI/CD with GitLab Flow

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: self-hosted
    
    steps:

      - name: Build Docker image
        run: docker build -t pariska/appjs:latest .

      - name: Login DockerHub
        run: docker login -u pariska -p  ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push image to DockerHub
        run: docker push pariska/appjs:latest
