name: Node.js CI/CD with GitLab Flow

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Build Docker image
        run: docker build -t node-app:latest .
